import logging
from datetime import datetime
from typing import List, Optional
from fastapi import HTTPException, status
from sqlalchemy.orm import Session
from sqlalchemy import func

from app.db.models import LoanApplicationModel, ApplicantModel, DocumentModel, UserModel
from app.schemas.customer import CustomerApplicationCreate
from app.services import (
    document_service,
    text_extraction_service,
    document_classification_service,
    field_extraction_service,
    document_validation_service,
    cross_document_verification_service,
    evidence_graph_service,
    review_score_service,
    human_review_service,
)
from app.services.cross_document_verification_service import get_application_profile_data
from app.ml.predictor import predict_application_risk

logger = logging.getLogger(__name__)


def generate_application_number(db: Session) -> str:
    """
    Generates an atomic, sequential backend loan application number.
    Format: GEN-{YEAR}-{6-digit sequence}, e.g. GEN-2026-000001.
    """
    current_year = datetime.utcnow().year
    prefix = f"GEN-{current_year}-"

    # Query all matching application numbers to find true max integer sequence
    app_numbers = (
        db.query(LoanApplicationModel.application_number)
        .filter(LoanApplicationModel.application_number.like(f"{prefix}%"))
        .all()
    )

    max_seq = 0
    for row in app_numbers:
        if row and row[0]:
            try:
                parts = row[0].split("-")
                seq_part = parts[-1]
                if seq_part.isdigit():
                    val = int(seq_part)
                    if val > max_seq:
                        max_seq = val
            except (ValueError, IndexError):
                pass

    return f"{prefix}{max_seq + 1:06d}"


def create_customer_application(
    db: Session,
    user: UserModel,
    data: CustomerApplicationCreate
) -> LoanApplicationModel:
    """
    Creates a new draft loan application owned by the authenticated customer.
    The application number is strictly generated by the backend.
    """
    app_number = generate_application_number(db)
    now = datetime.utcnow()

    # 1. Create primary loan application record
    app_obj = LoanApplicationModel(
        application_id=app_number,
        application_number=app_number,
        user_id=user.id,
        applicant_name=data.applicant_name.strip(),
        loan_amount=data.loan_amount,
        income_annum=data.income_annum or 0.0,
        status="DRAFT",
        created_at=now,
        updated_at=now,
    )
    db.add(app_obj)

    # 2. Create or sync associated applicant profile model for pipeline ML/verification compatibility
    try:
        seq_num = int(app_number.split("-")[-1])
    except Exception:
        seq_num = 1

    applicant_rec = ApplicantModel(
        applicant_id=app_number,
        loan_id=seq_num,
        applicant_name=data.applicant_name.strip(),
        employer=data.employer or "Self / Private",
        date_of_birth=data.date_of_birth or "1990-01-01",
        address=data.address or "India",
        education=data.education or "Graduate",
        self_employed=data.self_employed or "No",
        income_annum=data.income_annum or 0.0,
        monthly_income=(data.income_annum or 0.0) / 12.0,
        loan_amount=data.loan_amount,
        loan_term=data.loan_term or 12,
        cibil_score=750,
        residential_assets_value=(data.loan_amount * 1.5),
        commercial_assets_value=0.0,
        luxury_assets_value=0.0,
        bank_asset_value=(data.loan_amount * 0.4),
        historical_loan_status="Approved",
        scenario="customer_submission",
        created_at=now,
    )
    db.add(applicant_rec)

    db.commit()
    db.refresh(app_obj)

    logger.info(f"Created customer application {app_number} for customer {user.id} ({user.email})")
    return app_obj


def list_customer_applications(db: Session, user_id: str) -> List[LoanApplicationModel]:
    """
    Returns all applications owned by the specified customer.
    """
    return (
        db.query(LoanApplicationModel)
        .filter(LoanApplicationModel.user_id == user_id)
        .order_by(LoanApplicationModel.created_at.desc())
        .all()
    )


def get_customer_application(
    db: Session,
    user_id: str,
    application_id: str
) -> LoanApplicationModel:
    """
    Retrieves an application and strictly verifies customer ownership.
    Raises 404 if not found, 403 if owned by another customer.
    """
    app_obj = (
        db.query(LoanApplicationModel)
        .filter(
            (LoanApplicationModel.application_id == application_id) |
            (LoanApplicationModel.application_number == application_id)
        )
        .first()
    )

    if not app_obj:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Application '{application_id}' not found."
        )

    if app_obj.user_id != user_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied. You do not have permission to view or modify this application."
        )

    return app_obj


def upload_customer_document(
    db: Session,
    user_id: str,
    application_id: str,
    filename: str,
    content: bytes,
    document_type: str,
    content_type: Optional[str] = None
) -> DocumentModel:
    """
    Uploads a document to the customer's draft or additional-documents-required application after verifying ownership.
    """
    app_obj = get_customer_application(db, user_id, application_id)

    if app_obj.status not in ["DRAFT", "PENDING", "ADDITIONAL_DOCUMENTS_REQUIRED"]:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Cannot upload documents to application in '{app_obj.status}' status. Application is locked for review."
        )

    doc_obj = document_service.upload_document(
        db=db,
        application_id=app_obj.application_id,
        filename=filename,
        content=content,
        document_type=document_type,
        content_type=content_type,
        uploaded_by=user_id,
    )

    if app_obj.status == "ADDITIONAL_DOCUMENTS_REQUIRED":
        app_obj.status = "UNDER_REVIEW"
        app_obj.updated_at = datetime.utcnow()
        db.commit()
        try:
            run_application_processing_pipeline(db, app_obj.application_id)
        except Exception as e:
            logger.warning(f"Error re-running pipeline on document re-upload for {application_id}: {e}")
    else:
        app_obj.updated_at = datetime.utcnow()
        db.commit()

    return doc_obj


def delete_customer_document(
    db: Session,
    user_id: str,
    application_id: str,
    document_id: str
) -> bool:
    """
    Deletes an uploaded document from the customer's draft application after verifying ownership.
    """
    app_obj = get_customer_application(db, user_id, application_id)

    if app_obj.status not in ["DRAFT", "PENDING"]:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Cannot delete documents from application in '{app_obj.status}' status."
        )

    doc_obj = (
        db.query(DocumentModel)
        .filter(
            DocumentModel.document_id == document_id,
            DocumentModel.application_id == app_obj.application_id,
            DocumentModel.processing_status != "DELETED"
        )
        .first()
    )

    if not doc_obj:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Document '{document_id}' not found on application '{application_id}'."
        )

    success = document_service.delete_document(db, document_id)
    if success:
        app_obj.updated_at = datetime.utcnow()
        db.commit()

    return success


def run_application_processing_pipeline(db: Session, application_id: str) -> None:
    """
    Executes the existing document processing and analysis pipeline:
    1. Text extraction
    2. Classification
    3. Field extraction
    4. Document validation
    5. Cross-document verification
    6. Evidence graph construction
    7. ML risk prediction
    8. Review assessment scoring
    9. Human review gate evaluation
    """
    logger.info(f"Starting document intelligence pipeline for application {application_id}")

    # 1. Process each uploaded active document
    docs = document_service.list_documents_for_application(db, application_id)
    for doc in docs:
        try:
            text_extraction_service.extract_and_save_document_text(db, doc.document_id)
            document_classification_service.classify_document(db, doc.document_id)
            field_extraction_service.extract_and_save_fields(db, doc.document_id)
            document_validation_service.validate_and_save_document(db, doc.document_id)
        except Exception as e:
            logger.warning(f"Error processing document {doc.document_id} in pipeline: {e}")

    # 2. Application-level analysis
    try:
        cross_document_verification_service.verify_and_save_application(db, application_id)
    except Exception as e:
        logger.warning(f"Cross-document verification warning for {application_id}: {e}")

    try:
        evidence_graph_service.build_evidence_graph_for_application(db, application_id)
    except Exception as e:
        logger.warning(f"Evidence graph warning for {application_id}: {e}")

    try:
        profile = get_application_profile_data(db, application_id)
        predict_application_risk(application_id, profile)
    except Exception as e:
        logger.warning(f"ML risk prediction warning for {application_id}: {e}")

    try:
        review_score_service.compute_and_save_review_assessment(db, application_id)
    except Exception as e:
        logger.warning(f"Review score assessment warning for {application_id}: {e}")

    try:
        human_review_service.evaluate_human_review_gate(application_id, db=db, force_rebuild=True)
    except Exception as e:
        logger.warning(f"Human review gate warning for {application_id}: {e}")

    logger.info(f"Document intelligence pipeline completed for application {application_id}")


def submit_customer_application(
    db: Session,
    user_id: str,
    application_id: str
) -> LoanApplicationModel:
    """
    Submits a draft application, transitions status to SUBMITTED,
    and runs the automated processing pipeline.
    """
    app_obj = get_customer_application(db, user_id, application_id)

    if app_obj.status == "SUBMITTED":
        return app_obj

    # Check that at least one document has been uploaded
    docs = document_service.list_documents_for_application(db, app_obj.application_id)
    if not docs:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Cannot submit loan application without uploading documents. Please upload at least one required document."
        )

    # Transition status
    app_obj.status = "SUBMITTED"
    app_obj.updated_at = datetime.utcnow()
    db.commit()
    db.refresh(app_obj)

    # Run processing pipeline synchronously for instant availability
    try:
        run_application_processing_pipeline(db, app_obj.application_id)
    except Exception as e:
        logger.error(f"Error running pipeline on submission of {application_id}: {e}")

    db.refresh(app_obj)
    logger.info(f"Customer application {app_obj.application_id} successfully submitted by user {user_id}")
    return app_obj
