"""
Agent Review Schemas — Phase 16 AI Review Agent

Pydantic schemas for AI Loan Review Agent request, structured output,
investigation trace, and API responses.
"""

from datetime import datetime
from typing import Optional, List, Any, Dict
from pydantic import BaseModel, Field, ConfigDict


class InvestigationStepSchema(BaseModel):
    """A single recorded step in the agent investigation trace."""
    step_number: int = Field(..., description="1-indexed step number")
    action: str = Field(..., description="Action name (e.g., LOAD_CONTEXT, TOOL_CALL, BUILD_REVIEW)")
    tool_name: Optional[str] = Field(None, description="Tool invoked in this step")
    tool_input_summary: Optional[str] = Field(None, description="Summary of query or arguments")
    result_summary: str = Field(..., description="Concise summary of findings or outcome")
    reason: str = Field(..., description="Reasoning behind this step")
    evidence_ids: List[str] = Field(default_factory=list, description="Evidence node IDs referenced")
    policy_ids: List[str] = Field(default_factory=list, description="Policy section IDs referenced")


class AgentEvidenceReference(BaseModel):
    node_id: str = Field(..., description="Evidence node ID (e.g. NODE-FIELD-DOC001-name)")
    description: str = Field(..., description="Short human-readable description of the evidence")


class AgentPolicyReference(BaseModel):
    section_id: str = Field(..., description="Policy section ID from Phase 13 Knowledge Base")
    policy_name: str = Field(..., description="Name of the policy document")
    authority: str = Field(..., description="RBI or INTERNAL_BANK")
    policy_type: str = Field(..., description="REGULATORY or INTERNAL_UNDERWRITING")
    citation_text: str = Field(..., description="Verbatim or paraphrased text from the policy section")


class AgentFinalReviewSchema(BaseModel):
    """Structured review generated by the agent."""
    executive_summary: str = Field(..., description="Executive narrative for the loan officer")
    key_findings: List[str] = Field(default_factory=list, description="Key bullet-point findings")
    evidence_references: List[Dict[str, Any]] = Field(default_factory=list, description="Grounded evidence citations")
    policy_references: List[Dict[str, Any]] = Field(default_factory=list, description="Grounded policy citations")
    risk_interpretation: Optional[str] = Field("", description="Interpretation of ML risk model output")
    review_interpretation: Optional[str] = Field("", description="Interpretation of Review Score and Evidence Trust")
    unresolved_questions: List[str] = Field(default_factory=list, description="Questions remaining unresolved")
    recommended_next_step: str = Field(
        ...,
        description="Suggested action: STANDARD_REVIEW, OFFICER_INVESTIGATION, DOCUMENT_FOLLOWUP, or ESCALATE"
    )
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in review (0-1)")
    confidence_level: str = Field(..., description="LOW, MEDIUM, or HIGH")
    limitations: List[str] = Field(default_factory=list, description="Caveats or known data limitations")
    grounding_status: str = Field("GROUNDED", description="GROUNDED, PARTIAL, or UNGROUNDED")
    evidence_sufficiency: str = Field("SUFFICIENT", description="SUFFICIENT, PARTIAL, or INSUFFICIENT")
    claims_support_summary: Dict[str, str] = Field(default_factory=dict, description="SUPPORTED, UNSUPPORTED, UNKNOWN mapping")


class AgentReviewRequest(BaseModel):
    """Request body for POST /applications/{id}/agent/review."""
    force_rebuild: bool = Field(
        False,
        description="If True, re-runs the agent investigation even if cached review exists."
    )


class AgentReviewResponse(BaseModel):
    """Full API response for GET/POST /applications/{id}/agent/review."""
    model_config = ConfigDict(from_attributes=True)

    agent_review_id: str
    application_id: str
    agent_version: str
    instruction_version: str
    investigation_status: str  # COMPLETED, ESCALATED, DEGRADED, FAILED
    step_count: int
    tools_used: List[str] = []
    escalation_required: bool
    escalation_reason: Optional[str] = None
    injection_check_status: str  # CLEAN, FLAGGED
    grounding_status: str  # GROUNDED, PARTIAL, UNGROUNDED
    evidence_sufficiency: Optional[str] = "SUFFICIENT"
    confidence: Optional[float] = None
    confidence_level: Optional[str] = None
    retries_count: int = 0
    final_review: Dict[str, Any] = {}
    investigation_steps: List[Dict[str, Any]] = []
    created_at: Optional[str] = None
    completed_at: Optional[str] = None


class AgentTraceResponse(BaseModel):
    """API response for GET /applications/{id}/agent/trace."""
    model_config = ConfigDict(from_attributes=True)

    agent_review_id: str
    application_id: str
    agent_version: str
    instruction_version: str
    investigation_status: str
    step_count: int
    tools_used: List[str] = []
    retries_count: int = 0
    escalation_required: bool
    escalation_reason: Optional[str] = None
    investigation_steps: List[Dict[str, Any]] = []
    created_at: Optional[str] = None
    completed_at: Optional[str] = None
